name: schedule-extend-noip

on:
  push:
  schedule:
    - cron: '15 21 */9 * *'
jobs:
  extend-noip__main__:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7]
        poetry-version: [1.1.2]
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: install packages
        run: poetry install --no-dev
      - name: Run extend-noip
        env:
          NOIP_USERNAME: ${{ secrets.NOIP_USERNAME }}
          NOIP_PASSWORD: ${{ secrets.NOIP_PASSWORD }}
        run: |
          poetry run python -m extend_noip -s -d
          # -d show debug messages
          # -s turn of short delay (sleepon)
          # -i info only (no attempt to extend)